dev_dependencies:
mockito: ^5.0.15
collection: ^1.18.0
file: ^7.0.0
flutter_driver: ^0.0.0
fuchsia_remote_debug_protocol: ^0.0.0
integration_test: ^0.0.0
material_color_utilities: ^0.8.0
meta: ^1.10.0
platform: ^3.1.2
process: ^5.0.0
sdk: flutter
stack_trace: ^1.11.1
stream_channel: ^2.1.2
sync_http: ^0.3.1
test_api: ^0.6.0 
vm_service: ^11.10.0
webdriver: ^3.0.2



